---
title: "MagnusonK_WeekSeven"
author: "Ken Magnuson"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, message = FALSE, warning = FALSE}
library(caret)
library(rpart)
library(rpart.plot)
library(pROC)
library(gmodels)
library(vcd)
```

# Part A
```{r}
TP = 135
FP = 80
FN = 2
TN = 203

accuracy = (TP + TN) / (TP + TN + FP + FN)
error_rate = 1 - accuracy
expected_accuracy = ((TP + FN) * (TP + FP) + (FP + TN) * (FN + TN)) / ((TP + FP + FN + TN)^2)
kappa = (accuracy - expected_accuracy) / (1 - expected_accuracy)
sensitivity = TP / (TP + FN)
specificity = TN / (TN + FP)
precision = TP / (TP + FP)
recall = sensitivity
f_measure = 2 * ((precision * recall) / (precision + recall))

list(
  Accuracy = accuracy,
  ErrorRate = error_rate,
  Kappa = kappa,
  ExpectedAccuracy = expected_accuracy,
  Sensitivity = sensitivity,
  Specificity = specificity,
  Precision = precision,
  Recall = recall,
  FMeasure = f_measure
)
```


# Part B
# Step One
```{r}
heart = read.csv('heart_data.csv')
```

# Step Two
```{r}
print('Structure: heart')
str(heart)

print('Summary: heart')
summary(heart)
```

# Step Three
```{r}
heart$heartDisease = as.factor(heart$heartDisease)
```

# Step Four
```{r}
heart = na.omit(heart)
```

# Step Five
```{r}
set.seed(123)
train_index <- sample(seq_len(nrow(heart)), size = 0.8 * nrow(heart))
heart_train <- heart[train_index, ]
heart_test <- heart[-train_index, ]
```

# Step Six
```{r}
tree_model <- rpart(heartDisease ~ ., data = heart_train, method = "class")
rpart.plot(tree_model)
```

# Step Seven
```{r}
pred_class <- predict(tree_model, heart_test, type = "class")
```

# Step Eight
```{r}
head(pred_class)
```

# Step Nine
```{r}
confusion_matrix = table(Predicted = pred_class, Actual = heart_test$heartDisease)
confusion_matrix
```

# Step Ten
```{r}
CrossTable(confusion_matrix)
```

# Step Eleven
```{r}
Kappa(confusion_matrix)
```

# Step Twelve
```{r}
sensitivityValue <- sensitivity(pred_class, heart_test$heartDisease)
specificityValue <- specificity(pred_class, heart_test$heartDisease)
list(Sensitivity = sensitivityValue, Specificity = specificityValue)
```

# Step Thirteen
```{r}
precisionValue <- posPredValue(pred_class, heart_test$heartDisease)
recallValue <- sensitivityValue
fMeasureValue <- 2 * (precisionValue * recallValue) / (precisionValue + recallValue)
list(Precision = precisionValue, Recall = recallValue, F_Measure = fMeasureValue)
```

# Step Fourteen
```{r}
pred_prob <- predict(tree_model, heart_test, type = "prob")
```

# Step Fifteen
```{r}
head(pred_prob)
```

# Step Sixteen
```{r}
roc_curve <- roc(heart_test$heartDisease, pred_prob[, 2], levels = rev(levels(heart_test$heartDisease)))
plot(roc_curve, col = "blue", main = "ROC Curve")
abline(a = 0, b = 1, lty = 2)
```

# Step Seventeen
```{r}
auc_value <- auc(roc_curve)

performance_level <- ifelse(auc_value < 0.6, "Poor",
                      ifelse(auc_value < 0.7, "Fair",
                      ifelse(auc_value < 0.8, "Good",
                      ifelse(auc_value < 0.9, "Very Good", "Excellent"))))

list(AUC_Value = auc_value, Performance = performance_level)
```

# Step Eighteen
```{r}
set.seed(123)
folds <- createFolds(heart$heartDisease, k = 10, list = TRUE)
str(folds)
```

# Step Nineteen
```{r}
cv_results <- lapply(folds, function(fold_indices) {

  train_data <- heart[-fold_indices, ]
  test_data <- heart[fold_indices, ]

  cv_tree_model <- rpart(heartDisease ~ ., data = train_data, method = "class")
  cv_pred <- predict(cv_tree_model, test_data, type = "class")
  
  levels(cv_pred) <- levels(test_data$heartDisease)
  
  accuracy <- confusionMatrix(cv_pred, test_data$heartDisease)$overall['Accuracy']
  return(accuracy)
})

cv_results
```

# Step Twenty
```{r}
mean(unlist(cv_results))
```